name: Mandatory Tests

on:
  workflow_call:
    inputs:
      spreadsheet_id:
        required: true
        type: string
      authors_amount:
        required: true
        type: string
      worksheet_name:
        required: true
        type: string

jobs:
  mandatory-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter

      - name: Dart Analyze check
        id: dart_analyze
        uses: education/autograding-command-grader@v1
        with:
          test-name: Dart Analyze check
          command: dart analyze
          timeout: 10
          max-score: 1

      - name: Test 1
        id: m_test1
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Navegacao - Tem uma bottom bar com 4 opcoes"
          command: flutter test --name "Navegacao - Tem uma bottom bar com 4 opcoes"
          timeout: 10
          max-score: 1

      - name: Test 2
        id: m_test2
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Navegacao - Bottom bar navega para os 4 ecras"
          command: flutter test --name "Navegacao - Bottom bar navega para os 4 ecras"
          timeout: 10
          max-score: 1

      - name: Test 3
        id: m_test3
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Lista estacoes - Apresenta estacoes"
          command: flutter test --name "Lista estacoes - Apresenta estacoes"
          timeout: 10
          max-score: 1

      - name: Test 4
        id: m_test4
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Lista estacoes - Navega para o detalhe da estacao escolhida"
          command: flutter test --name "Lista estacoes - Navega para o detalhe da estacao escolhida"
          timeout: 10
          max-score: 1

      - name: Test 5
        id: m_test5
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Incidentes - Existencia de campos do formulario e botao de submeter"
          command: flutter test --name "Incidentes - Existencia de campos do formulario e botao de submeter"
          timeout: 10
          max-score: 1

      - name: Test 6
        id: m_test6
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Incidentes - Valicadoes de erro"
          command: flutter test --name "Incidentes - Valicadoes de erro"
          timeout: 10
          max-score: 1

      - name: Test 7
        id: m_test7
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Incidentes - Inserir incidente"
          command: flutter test --name "Incidentes - Inserir incidente"
          timeout: 10
          max-score: 1

      - name: Test 8
        id: m_test8
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Detalhe - Apresenta incidente"
          command: flutter test --name "Detalhe - Apresenta incidente"
          timeout: 10
          max-score: 1

      - name: Test 9
        id: m_test9
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Lista estacoes - Com delay"
          command: flutter test --name "Lista estacoes - Com delay"
          timeout: 10
          max-score: 1

      - name: Test 10
        id: m_test10
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Mapa estacoes - Apresenta estacoes"
          command: flutter test --name "Mapa estacoes - Apresenta estacoes"
          timeout: 10
          max-score: 1

      - name: Autograding Reporter
        uses: mstavares/autograding-grading-reporter@v1.0.5
        with:
          runners: dart_analyze,m_test1,m_test2,m_test3,m_test4,m_test5,m_test6,m_test7,m_test8,m_test9,m_test10
        env:
          DART_ANALYZE_RESULTS: ${{ steps.dart_analyze.outputs.result }}
          M_TEST1_RESULTS: ${{ steps.m_test1.outputs.result }}
          M_TEST2_RESULTS: ${{ steps.m_test2.outputs.result }}
          M_TEST3_RESULTS: ${{ steps.m_test3.outputs.result }}
          M_TEST4_RESULTS: ${{ steps.m_test4.outputs.result }}
          M_TEST5_RESULTS: ${{ steps.m_test5.outputs.result }}
          M_TEST6_RESULTS: ${{ steps.m_test6.outputs.result }}
          M_TEST7_RESULTS: ${{ steps.m_test7.outputs.result }}
          M_TEST8_RESULTS: ${{ steps.m_test8.outputs.result }}
          M_TEST9_RESULTS: ${{ steps.m_test9.outputs.result }}
          M_TEST10_RESULTS: ${{ steps.m_test10.outputs.result }}
          SHEETS_CREDENTIALS: ${{ secrets.SHEETS_CREDENTIALS }}
          SPREADSHEET_ID: ${{ inputs.spreadsheet_id }}
          AUTHORS_AMOUNT: ${{ inputs.authors_amount }}
          WORKSHEET_NAME: ${{ inputs.worksheet_name }}
