name: Optional Tests

on:
  workflow_call:
    inputs:
      spreadsheet_id:
        required: true
        type: string
      authors_amount:
        required: true
        type: string
      worksheet_name:
        required: true
        type: string

jobs:
  optional-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter

      - name: Test 1
        id: o_test1
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Lista estacoes - Offline - Apresentar mensagem de erro ao inicializar sem estacoes"
          command: flutter test --name "Lista estacoes - Offline - Apresentar mensagem de erro ao inicializar sem estacoes"
          timeout: 10
          max-score: 1

      - name: Test 2
        id: o_test2
        uses: education/autograding-command-grader@v1
        with:
          test-name: "Offline - Atualizar estacoes quando ao voltar a ficar online"
          command: flutter test --name "Offline - Atualizar estacoes quando ao voltar a ficar online"
          timeout: 10
          max-score: 1

      - name: Autograding Reporter
        uses: mstavares/autograding-grading-reporter@v1.0.5
        with:
          runners: o_test1,o_test2
        env:
          O_TEST1_RESULTS: ${{ steps.o_test1.outputs.result }}
          O_TEST2_RESULTS: ${{ steps.o_test2.outputs.result }}
          SHEETS_CREDENTIALS: ${{ secrets.SHEETS_CREDENTIALS }}
          SPREADSHEET_ID: ${{ inputs.spreadsheet_id  }}
          AUTHORS_AMOUNT: ${{ inputs.authors_amount }}
          WORKSHEET_NAME: ${{ inputs.worksheet_name }}
